### PR TITLE
Fix json overrides

### LINKED ISSUE #66: Problems with overriding via yaml?
I noticed that when adding a `smtp.yaml` to the config path, the values are not being loaded on startup.

Example: no `smtp.ini` present in config path and `smtp.yaml` has contents
```yaml
"!smtp.ini":
  "main":
     "nodes": 0
"!smtpgreeting": [ "This is some custom greeting!"]
```
The logoutput on startup then includes:

```
Overriding file smtp.ini with config from /usr/local/haraka/config/smtp.yaml
Overriding file smtpgreeting with config from /usr/local/haraka/config/smtp.yaml
```

```
[WARN] [-] [core] smtp.ini.nodes unset, using 1, see https://github.com/haraka/Haraka/wiki/Performance-Tuning
```
which tells me, that my override was not applied.

Printing out the contents of `Server.cfg` at where this message is being printed yields:

```json
{
  "main": {
     "daemonize":false,
     "strict_rfc1869":false,
     "smtputf8":true,
     "graceful_shutdown":false
  },
 "headers":{
     "add_received":true,
     "show_version":true,
     "clean_auth_results":true
 }
}
```
which apparently are the passed default booleans in the `Server.config.get('smtp.ini'......` call in `Server.load_smtp_ini`.

Weirdly enough, the `!smtpgreeting` override works and is being loaded/used.

edit: this problem only applies to `.ini` file overrides

I also tried to comment out the default booleans in `Server.load_smtp_ini` and in this case the `!smpt.ini` override is being loaded correctly.

I suspect that there could be a problem in `configfile.js`, specifically in `get_cache_key()` regarding the way booleans are handled there since I noticed that they get appended to the name for some reason?

Maybe I also have a misconception about how this mechanism is supposed to work, especially regarding the booleans.
The documentation is a little bit sparse on this detail.

Any help or pointers would be welcome!

### LINKED ISSUE #68: Add option to load main config in the beginning
The [README](https://github.com/haraka/haraka-config#json-files) mentions that it is possible to have one JSON / YAML file containing the configuration for different files. I really like that because Haraka uses many different configuration files.

However, I think (if I understood the code correctly) that the config loader can only use cached results from such a file if it has been loaded before. But I didn't find any option to load an additional config file on startup (of course it's possible via a plugin). So the only possibility of using the feature mentioned above I could find is to abuse a JSON / YAML config file that is loaded and include other configuration files in it (using the `!` syntax). Additionally, I am not sure if there even are any JSON / YAML files that are loaded on startup by default and there always has to be a `smtp.*` (otherwise Haraka terminates), so that file can not be replaced easily

So it's really hacky to use the `!` syntax to keep all configuration options in one main config file. Maybe a possible solution could be to load a main configuration file (e.g. `main.json` or `main.yaml`) on startup if present so all other configuration files can theoretically be defined there with the `!` syntax if somebody prefers to do so.

### LINKED ISSUE #69: smtp.json / smtp.yaml are not loaded properly
**Describe the bug**

Haraka does not load `smtp.yaml` or `smtp.json` if `smtp.ini` does not exist.

**Expected behavior**

Haraka should either crash although `smtp.json` or `smtp.yaml` is present or it should load one of them.

**Observed behavior**

The existence of `smtp.json` or `smtp.yaml` prevents Haraka from crashing. See [this check](https://github.com/haraka/Haraka/blob/d7e37ebbf9587074d00ad06123053681123cf945/bin/haraka#L644).

**Steps To Reproduce**

- `haraka --install "${HARAKA_HOME}"`
- first case: `rm "${HARAKA_HOME}/config/smtp.ini"`
  - Haraka does crash when started.
- second case: `mv "${HARAKA_HOME}/config/smtp.ini" "${HARAKA_HOME}/config/smtp.yaml"`
  - Haraka does not crash when started.
  - When putting log statements in the [config loader](https://github.com/haraka/haraka-config/blob/eb3cd487460df731d8a99a2ee8f5cebd6ed1ea5c/configfile.js#L186), one can observe that only `smtp.ini` is requested. `smtp.yaml` or `smtp.json` are never requested.
  - If a JSON / HJSON file is not found, the loader checks whether the same file with `.yaml` exists (see [here](https://github.com/haraka/haraka-config/blob/eb3cd487460df731d8a99a2ee8f5cebd6ed1ea5c/configfile.js#L289)). This is not done for INI files.

**System Info:**

Haraka | Haraka.js — Version: 3.0.1
 --- | :---
Node | v19.7.0
OS | Linux 060427c22453 6.2.8-arch1-1 haraka/Haraka#1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 Linux
openssl | OpenSSL 3.0.8 7 Feb 2023 (Library: OpenSSL 3.0.8 7 Feb 2023)

**Additional context**

Haraka runs inside an Alpine Docker container with Alpine version 3.17.2.

### PR DESCRIPTION
**Pull request by louis-lau**
Found some vague references to a single file config option. After figuring out how to use, it didn't really seem to work. So I dug in and fixed it!

- Loading `smtp.json` seems to have been accidentally removed in this commit 8 years ago from what I can tell:
  https://github.com/haraka/Haraka/commit/fefae7cdfca43241182ffe2be3f60091a547ca69
- `this._overrides` was checked, but there wasn't any code setting values there. Must have been accidentally removed at some point as well.
- Also added some more details/example to the doc for using this so there's less to figure out.

Fixes #69
Fixes #68
Fixes #66

### CODE REVIEW

File: config.js [hunk 1]
```diff
@@ -157,3 +157,6 @@ function merge_struct(defaults, overrides) {
   }
   return defaults
 }
+
+// Load smtp.json or smtp.yaml as early as possible
```
Comment (msimerson) [inline config.js:161]:
```suggestion
// JSON overrides needs smtp.(json|hjson|yaml) loaded early
```

**Review by msimerson — APPROVED** [review]

**Comment by msimerson** [comment]
thanks @louis-lau !

**Comment by louis-lau** [comment]
Thanks for the quick merge!
